-- babymon: generated by tools/content-editor (do not hand-edit;
-- re-Save from the content editor, or maintain editor_project.lua).
return function(mod)

  mod.content.palettes:patch("pokemon", {
    BURGELA = {
      normal = {
        { 99, 255, 90 },
        { 140, 49, 49 },
      },
      shiny = {
        { 165, 230, 90 },
        { 140, 49, 49 },
      },
    },
    VULPIII = {
      normal = {
        { 255, 148, 74 },
        { 189, 74, 82 },
      },
      shiny = {
        { 255, 197, 8 },
        { 181, 132, 8 },
      },
    },
  })

  mod.content.pokemon:register("BURGELA", {
    baseExp = 166,
    baseStats = {
      attack = 40,
      defense = 100,
      hp = 50,
      specialAttack = 85,
      specialDefense = 45,
      speed = 40,
    },
    catchRate = 45,
    cry = "TANGELA",
    dex = 252,
    eggGroups = {
      "EGG_NONE",
      "EGG_NONE",
    },
    eggMoves = {
      "FLAIL",
      "CONFUSION",
      "MEGA_DRAIN",
      "REFLECT",
      "AMNESIA",
    },
    eggSteps = 20,
    evolutions = {
      {
              into = "TANGELA",
              method = "EVOLVE_HAPPINESS",
              time = "ANYTIME",
            },
    },
    genderRatio = 127,
    growthRate = "GROWTH_MEDIUM_FAST",
    growthRateId = 0,
    id = "BURGELA",
    index = 252,
    items = {},
    levelMoves = {
      {
              level = 1,
              move = "CONSTRICT",
            },
      {
              level = 4,
              move = "SLEEP_POWDER",
            },
      {
              level = 8,
              move = "BIND",
            },
      {
              level = 13,
              move = "GROWTH",
            },
      {
              level = 19,
              move = "VINE_WHIP",
            },
      {
              level = 23,
              move = "SLEEP_POWDER",
            },
      {
              level = 26,
              move = "STUN_SPORE",
            },
      {
              level = 29,
              move = "POISONPOWDER",
            },
      {
              level = 34,
              move = "NIGHT_SHADE",
            },
      {
              level = 40,
              move = "SLAM",
            },
    },
    name = "BURGELA",
    picSize = 6,
    spriteBack = mod.path .. "/assets/Burgela-back.png",
    spriteFront = mod.path .. "/assets/Burgela-front.png",
    tmhm = {
      "HEADBUTT",
      "CURSE",
      "TOXIC",
      "PSYCH_UP",
      "HIDDEN_POWER",
      "SUNNY_DAY",
      "SWEET_SCENT",
      "SNORE",
      "HYPER_BEAM",
      "PROTECT",
      "GIGA_DRAIN",
      "ENDURE",
      "FRUSTRATION",
      "SOLARBEAM",
      "RETURN",
      "DOUBLE_TEAM",
      "SWAGGER",
      "SLEEP_TALK",
      "SLUDGE_BOMB",
      "REST",
      "ATTRACT",
      "THIEF",
      "CUT",
      "FLASH",
    },
    types = {
      "GRASS",
      "GRASS",
    },
  })

  mod.content.icons:override("BURGELA", "ICON_ODDISH")

  mod.content.pokemon:patch("TANGELA", {
    baseExp = 166,
    baseStats = {
      attack = 55,
      defense = 115,
      hp = 65,
      specialAttack = 100,
      specialDefense = 40,
      speed = 60,
    },
    catchRate = 45,
    cry = "TANGELA",
    dex = 114,
    eggGroups = {
      "EGG_PLANT",
      "EGG_PLANT",
    },
    eggGroupsRaw = 119,
    eggMoves = {},
    eggSteps = 20,
    evolutions = {},
    genderRatio = 127,
    growthRate = "GROWTH_MEDIUM_FAST",
    growthRateId = 0,
    id = "TANGELA",
    index = 114,
    items = {},
    levelMoves = {
      {
              level = 1,
              move = "CONSTRICT",
            },
      {
              level = 4,
              move = "SLEEP_POWDER",
            },
      {
              level = 10,
              move = "ABSORB",
            },
      {
              level = 13,
              move = "POISONPOWDER",
            },
      {
              level = 19,
              move = "VINE_WHIP",
            },
      {
              level = 25,
              move = "BIND",
            },
      {
              level = 31,
              move = "MEGA_DRAIN",
            },
      {
              level = 34,
              move = "STUN_SPORE",
            },
      {
              level = 40,
              move = "SLAM",
            },
      {
              level = 46,
              move = "GROWTH",
            },
    },
    name = "TANGELA",
    picSize = 6,
    tmhm = {
      "HEADBUTT",
      "CURSE",
      "TOXIC",
      "PSYCH_UP",
      "HIDDEN_POWER",
      "SUNNY_DAY",
      "SWEET_SCENT",
      "SNORE",
      "HYPER_BEAM",
      "PROTECT",
      "GIGA_DRAIN",
      "ENDURE",
      "FRUSTRATION",
      "SOLARBEAM",
      "RETURN",
      "DOUBLE_TEAM",
      "SWAGGER",
      "SLEEP_TALK",
      "SLUDGE_BOMB",
      "REST",
      "ATTRACT",
      "THIEF",
      "CUT",
      "FLASH",
    },
    tmhmRaw = { 38, 95, 61, 132, 14, 56, 68, 0 },
    types = {
      "GRASS",
      "GRASS",
    },
  })

  mod.content.pokemon:register("VULPIII", {
    baseExp = 63,
    baseStats = {
      attack = 26,
      defense = 25,
      hp = 23,
      specialAttack = 40,
      specialDefense = 60,
      speed = 45,
    },
    catchRate = 190,
    cry = "VULPIX",
    dex = 253,
    eggGroups = {
      "EGG_NONE",
      "EGG_NONE",
    },
    eggMoves = {
      "FAINT_ATTACK",
      "HYPNOSIS",
      "FLAIL",
      "SPITE",
      "DISABLE",
    },
    eggSteps = 20,
    evolutions = {
      {
              into = "VULPIX",
              method = "EVOLVE_HAPPINESS",
              time = "ANYTIME",
            },
    },
    genderRatio = 191,
    growthRate = "GROWTH_MEDIUM_FAST",
    growthRateId = 0,
    id = "VULPIII",
    index = 253,
    items = {
      "BURNT_BERRY",
      "BURNT_BERRY",
    },
    levelMoves = {
      {
              level = 1,
              move = "TAIL_WHIP",
            },
      {
              level = 4,
              move = "QUICK_ATTACK",
            },
      {
              level = 7,
              move = "ROAR",
            },
      {
              level = 11,
              move = "EMBER",
            },
      {
              level = 13,
              move = "FORESIGHT",
            },
      {
              level = 20,
              move = "FIRE_SPIN",
            },
      {
              level = 25,
              move = "CONFUSE_RAY",
            },
      {
              level = 31,
              move = "DOUBLE_TEAM",
            },
      {
              level = 37,
              move = "FLAMETHROWER",
            },
    },
    name = "VULPIII",
    picSize = 6,
    spriteBack = mod.path .. "/assets/Vulpiii-back.png",
    spriteFront = mod.path .. "/assets/Vulpiii-front.png",
    tmhm = {
      "HEADBUTT",
      "CURSE",
      "TOXIC",
      "HIDDEN_POWER",
      "SUNNY_DAY",
      "SNORE",
      "PROTECT",
      "ENDURE",
      "FRUSTRATION",
      "IRON_TAIL",
      "RETURN",
      "DIG",
      "DOUBLE_TEAM",
      "SWAGGER",
      "SLEEP_TALK",
      "FIRE_BLAST",
      "SWIFT",
      "REST",
      "ATTRACT",
    },
    types = {
      "FIRE",
      "FIRE",
    },
  })

  mod.content.icons:override("VULPIII", "ICON_FOX")

  mod.content.pokemon:patch("VULPIX", {
    baseExp = 63,
    baseStats = {
      attack = 41,
      defense = 40,
      hp = 38,
      specialAttack = 50,
      specialDefense = 65,
      speed = 65,
    },
    catchRate = 190,
    dex = 37,
    eggGroups = {
      "EGG_GROUND",
      "EGG_GROUND",
    },
    eggGroupsRaw = 85,
    eggMoves = {},
    eggSteps = 20,
    evolutions = {
      {
              into = "NINETALES",
              item = "FIRE_STONE",
              method = "EVOLVE_ITEM",
            },
    },
    genderRatio = 191,
    growthRate = "GROWTH_MEDIUM_FAST",
    growthRateId = 0,
    id = "VULPIX",
    index = 37,
    items = {
      "BURNT_BERRY",
      "BURNT_BERRY",
    },
    levelMoves = {
      {
              level = 1,
              move = "EMBER",
            },
      {
              level = 1,
              move = "TAIL_WHIP",
            },
      {
              level = 7,
              move = "QUICK_ATTACK",
            },
      {
              level = 13,
              move = "ROAR",
            },
      {
              level = 19,
              move = "CONFUSE_RAY",
            },
      {
              level = 25,
              move = "SAFEGUARD",
            },
      {
              level = 31,
              move = "FLAMETHROWER",
            },
      {
              level = 37,
              move = "FIRE_SPIN",
            },
    },
    name = "VULPIX",
    picSize = 6,
    tmhm = {
      "HEADBUTT",
      "CURSE",
      "TOXIC",
      "HIDDEN_POWER",
      "SUNNY_DAY",
      "SNORE",
      "PROTECT",
      "ENDURE",
      "FRUSTRATION",
      "IRON_TAIL",
      "RETURN",
      "DIG",
      "DOUBLE_TEAM",
      "SWAGGER",
      "SLEEP_TALK",
      "FIRE_BLAST",
      "SWIFT",
      "REST",
      "ATTRACT",
    },
    tmhmRaw = { 38, 22, 89, 140, 102, 24, 0, 0 },
    types = {
      "FIRE",
      "FIRE",
    },
  })

  -- Gold pokedex entries (gen2Pokedex.entries)
  do
    local _dex = {
      ["BURGELA"] = {
        height = 209,
        id = "BURGELA",
        kind = "VINE",
        text = "It grows around<NEXT>coasts and swamps by using the",
        text2 = "salt for nutrients.",
        weight = 40,
      },
      ["VULPIII"] = {
        height = 100,
        id = "VULPIII",
        kind = "FOX",
        text = "Its fire breath<NEXT>does not come in<NEXT> until its tail",
        text2 = "splitting begins.",
        weight = 110,
      },
    }
    mod.events:on("mods.loaded", function(ev)
      local data = ev and ev.data
      if type(data) ~= "table" then return end
      local dex = data.gen2Pokedex or data.pokedex
      if type(dex) ~= "table" then
        dex = { entries = {} }
        data.gen2Pokedex = dex; data.pokedex = dex
      end
      dex.entries = dex.entries or {}
      for id, patch in pairs(_dex) do
        local row = dex.entries[id] or {}
        for k, v in pairs(patch) do row[k] = v end
        dex.entries[id] = row
      end
    end)
  end

  mod.content.cries:register("BURGELA", { base = "TANGELA" })

  mod.content.cries:register("VULPIII", { base = "VULPIX" })

end
